application: seqalign
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images 
- url: /.*
  script: main.application
